# Agent HTTP API on Cloud Run, protected by IAP, reading the data lake from Cloud Storage.
#
# The Cloud Run service itself is deployed by GitHub Actions on the agent repository, not by
# Terraform (see README, "Cloud Run is deployed outside Terraform"). Terraform owns its
# runtime account, secrets, data bucket and the service-scoped IAP/invoker IAM; the env maps
# below are exported as outputs so the workflow deploys with the same configuration.

locals {
  image_registry = "${var.region}-docker.pkg.dev/${var.project_id}/${var.artifact_repository_id}"

  # Secret Manager holds the values; Terraform only creates the containers, so no key ever
  # reaches the Terraform state. Values are added with `gcloud secrets versions add`.
  secrets = {
    openai_api_key        = "openai-api-key"
    cloudflare_account_id = "cloudflare-account-id"
    cloudflare_api_token  = "cloudflare-api-token"
    openrouter_api_key    = "openrouter-api-key"
    # Organizers' S3 bucket, read by the data pipeline job (pipeline.tf).
    aws_access_key_id     = "aws-access-key-id"
    aws_secret_access_key = "aws-secret-access-key"
    slack_webhook_url     = "slack-webhook-url"
    # Telegram channel of the case flow: the BotFather token and the setWebhook secret_token.
    telegram_bot_token      = "telegram-bot-token"
    telegram_webhook_secret = "telegram-webhook-secret"
  }

  agent_secret_env = merge(
    {
      LLM_API_KEY    = "openai_api_key"
      OPENAI_API_KEY = "openai_api_key"
    },
    var.jev_enabled ? {
      CLOUDFLARE_ACCOUNT_ID = "cloudflare_account_id"
      CLOUDFLARE_API_TOKEN  = "cloudflare_api_token"
    } : {},
    var.slack_enabled ? { SLACK_WEBHOOK_URL = "slack_webhook_url" } : {},
    # The operator service tells the customer in Telegram how a specialist decided.
    var.telegram_enabled ? {
      TELEGRAM_BOT_TOKEN      = "telegram_bot_token"
      TELEGRAM_WEBHOOK_SECRET = "telegram_webhook_secret"
    } : {},
    startswith(var.decision_llm_model, "openrouter/") ? {
      OPENROUTER_API_KEY = "openrouter_api_key"
    } : {},
  )

  agent_env = merge(
    {
      ENVIRONMENT = "production"
      LLM_MODEL   = var.llm_model
      # Hosted provider: no self-hosted base URL.
      LLM_API_BASE = ""
      STORE        = var.agent_store
      JEV_ENABLED  = var.jev_enabled ? "1" : "0"
      DECISIONS    = var.decisions

      # Both services share cases, case files and approval requests: the case flow creates
      # them and the specialist decides in the operator back office.
      GOOGLE_CLOUD_PROJECT        = var.project_id
      CASE_STORE                  = "firestore"
      CASE_REPOSITORY             = "firestore"
      APPROVAL_REPOSITORY         = "firestore"
      FIRESTORE_DATABASE          = google_firestore_database.default.name
      FIRESTORE_COLLECTION_PREFIX = var.firestore_collection_prefix
      BACKOFFICE_ENABLED          = "true"
    },
    var.decision_llm_model == "" ? {} : { DECISION_LLM_MODEL = var.decision_llm_model },
    var.reference_date == "" ? {} : { REFERENCE_DATE = var.reference_date },
    # Operator API behind IAP only: return how each turn was decided with the reply.
    var.expose_trace ? { EXPOSE_TRACE = "true" } : {},
    var.public_base_url == "" ? {} : { PUBLIC_BASE_URL = var.public_base_url },
    var.slack_assignees == "" ? {} : { SLACK_ASSIGNEES = var.slack_assignees },
    # Examples in the API docs: a customer that exists in the data the service reads.
    var.api_example_customer_id == "" ? {} : { API_EXAMPLE_CUSTOMER_ID = var.api_example_customer_id },
    var.api_example_message == "" ? {} : { API_EXAMPLE_MESSAGE = var.api_example_message },
  )

  iap_members = toset(concat(keys(var.team_members), var.iap_members))
}

resource "google_artifact_registry_repository" "images" {
  repository_id = var.artifact_repository_id
  location      = var.region
  format        = "DOCKER"
  description   = "Container images of the Lir agent and data pipeline."

  depends_on = [google_project_service.enabled]
}

resource "google_storage_bucket" "data" {
  name                        = "${var.project_id}-data"
  location                    = var.region
  uniform_bucket_level_access = true
  public_access_prevention    = "enforced"
  # The data lake is regenerated by the pipeline job; never destroy it by accident.
  force_destroy = false

  depends_on = [google_project_service.enabled]
}

resource "google_secret_manager_secret" "this" {
  for_each = local.secrets

  secret_id = each.value
  replication {
    auto {}
  }

  depends_on = [google_project_service.enabled]
}

# ---- runtime identity -------------------------------------------------------------------

resource "google_service_account" "agent" {
  account_id   = "${var.agent_service_name}-run"
  display_name = "Lir agent (Cloud Run runtime)"
}

resource "google_storage_bucket_iam_member" "agent_reads_data" {
  bucket = google_storage_bucket.data.name
  role   = "roles/storage.objectViewer"
  member = google_service_account.agent.member
}

resource "google_secret_manager_secret_iam_member" "agent" {
  for_each = toset(values(local.agent_secret_env))

  secret_id = google_secret_manager_secret.this[each.value].id
  role      = "roles/secretmanager.secretAccessor"
  member    = google_service_account.agent.member
}

# ---- service ----------------------------------------------------------------------------

# The service moved to GitHub Actions. Forget it without destroying the live service; this
# block can be deleted once every state that held the resource has been applied.
removed {
  from = google_cloud_run_v2_service.agent

  lifecycle {
    destroy = false
  }
}

# ---- IAP --------------------------------------------------------------------------------

resource "google_project_service_identity" "iap" {
  provider = google-beta
  service  = "iap.googleapis.com"

  depends_on = [google_project_service.enabled]
}

# IAP forwards authenticated requests with its own identity.
# Service-scoped (least privilege): only created once the service exists (two-phase apply).
resource "google_cloud_run_v2_service_iam_member" "iap_invoker" {
  count = var.agent_service_deployed ? 1 : 0

  name     = var.agent_service_name
  location = var.region
  role     = "roles/run.invoker"
  member   = google_project_service_identity.iap.member
}

resource "google_iap_web_cloud_run_service_iam_member" "users" {
  for_each = var.agent_service_deployed ? local.iap_members : toset([])

  location               = var.region
  cloud_run_service_name = var.agent_service_name
  role                   = "roles/iap.httpsResourceAccessor"
  member                 = "user:${each.value}"
}
