# Agent HTTP API on Cloud Run, protected by IAP, reading the data lake from Cloud Storage.

locals {
  image_registry = "${var.region}-docker.pkg.dev/${var.project_id}/${var.artifact_repository_id}"

  # Secret Manager holds the values; Terraform only creates the containers, so no key ever
  # reaches the Terraform state. Values are added with `gcloud secrets versions add`.
  secrets = {
    openai_api_key        = "openai-api-key"
    cloudflare_account_id = "cloudflare-account-id"
    cloudflare_api_token  = "cloudflare-api-token"
    aws_access_key_id     = "aws-access-key-id"
    aws_secret_access_key = "aws-secret-access-key"
    openrouter_api_key    = "openrouter-api-key"
  }

  agent_secret_env = merge(
    {
      LLM_API_KEY    = "openai_api_key"
      OPENAI_API_KEY = "openai_api_key"
    },
    var.jev_enabled ? {
      CLOUDFLARE_ACCOUNT_ID = "cloudflare_account_id"
      CLOUDFLARE_API_TOKEN  = "cloudflare_api_token"
    } : {},
    startswith(var.decision_llm_model, "openrouter/") ? {
      OPENROUTER_API_KEY = "openrouter_api_key"
    } : {},
  )

  agent_env = merge(
    {
      ENVIRONMENT = "production"
      LLM_MODEL   = var.llm_model
      # Hosted provider: no self-hosted base URL.
      LLM_API_BASE = ""
      STORE        = var.agent_store
      JEV_ENABLED  = var.jev_enabled ? "1" : "0"
      DECISIONS    = var.decisions
    },
    var.decision_llm_model == "" ? {} : { DECISION_LLM_MODEL = var.decision_llm_model },
    var.reference_date == "" ? {} : { REFERENCE_DATE = var.reference_date },
  )

  iap_members = toset(concat(keys(var.team_members), var.iap_members))
  deploy      = var.agent_image != ""
}

resource "google_artifact_registry_repository" "images" {
  repository_id = var.artifact_repository_id
  location      = var.region
  format        = "DOCKER"
  description   = "Container images of the Lir agent and data pipeline."

  depends_on = [google_project_service.enabled]
}

resource "google_storage_bucket" "data" {
  name                        = "${var.project_id}-data"
  location                    = var.region
  uniform_bucket_level_access = true
  public_access_prevention    = "enforced"
  # The data lake is regenerated by the pipeline job; never destroy it by accident.
  force_destroy = false

  depends_on = [google_project_service.enabled]
}

resource "google_secret_manager_secret" "this" {
  for_each = local.secrets

  secret_id = each.value
  replication {
    auto {}
  }

  depends_on = [google_project_service.enabled]
}

# ---- runtime identity -------------------------------------------------------------------

resource "google_service_account" "agent" {
  account_id   = "${var.agent_service_name}-run"
  display_name = "Lir agent (Cloud Run runtime)"
}

resource "google_storage_bucket_iam_member" "agent_reads_data" {
  bucket = google_storage_bucket.data.name
  role   = "roles/storage.objectViewer"
  member = google_service_account.agent.member
}

resource "google_secret_manager_secret_iam_member" "agent" {
  for_each = toset(values(local.agent_secret_env))

  secret_id = google_secret_manager_secret.this[each.value].id
  role      = "roles/secretmanager.secretAccessor"
  member    = google_service_account.agent.member
}

# ---- service ----------------------------------------------------------------------------

resource "google_cloud_run_v2_service" "agent" {
  count    = local.deploy ? 1 : 0
  provider = google-beta

  name                = var.agent_service_name
  location            = var.region
  ingress             = "INGRESS_TRAFFIC_ALL"
  iap_enabled         = true
  deletion_protection = false

  template {
    service_account       = google_service_account.agent.email
    execution_environment = "EXECUTION_ENVIRONMENT_GEN2"

    scaling {
      min_instance_count = 0
      max_instance_count = var.agent_max_instances
    }

    containers {
      image = var.agent_image

      ports {
        container_port = 8080
      }

      resources {
        limits = {
          cpu    = "1"
          memory = "1Gi"
        }
      }

      dynamic "env" {
        for_each = local.agent_env
        content {
          name  = env.key
          value = env.value
        }
      }

      dynamic "env" {
        for_each = local.agent_secret_env
        content {
          name = env.key
          value_source {
            secret_key_ref {
              secret  = google_secret_manager_secret.this[env.value].secret_id
              version = "latest"
            }
          }
        }
      }

      volume_mounts {
        name       = "data"
        mount_path = "/mnt/data"
      }

      startup_probe {
        http_get {
          path = "/health"
        }
      }
    }

    volumes {
      name = "data"
      gcs {
        bucket    = google_storage_bucket.data.name
        read_only = true
      }
    }
  }

  depends_on = [
    google_secret_manager_secret_iam_member.agent,
    google_storage_bucket_iam_member.agent_reads_data,
  ]
}

# ---- IAP --------------------------------------------------------------------------------

resource "google_project_service_identity" "iap" {
  provider = google-beta
  service  = "iap.googleapis.com"

  depends_on = [google_project_service.enabled]
}

# IAP forwards authenticated requests with its own identity.
resource "google_cloud_run_v2_service_iam_member" "iap_invoker" {
  count = local.deploy ? 1 : 0

  name     = google_cloud_run_v2_service.agent[0].name
  location = var.region
  role     = "roles/run.invoker"
  member   = google_project_service_identity.iap.member
}

resource "google_iap_web_cloud_run_service_iam_member" "users" {
  for_each = local.deploy ? local.iap_members : toset([])

  location               = var.region
  cloud_run_service_name = google_cloud_run_v2_service.agent[0].name
  role                   = "roles/iap.httpsResourceAccessor"
  member                 = "user:${each.value}"
}
